// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.ASCII85Encoder
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("original_text")]
        public string OriginalText { get; set; }

        [JsonProperty("encoded")]
        public string Encoded { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }

        [JsonProperty("original_length")]
        public long OriginalLength { get; set; }

        [JsonProperty("encoded_length")]
        public long EncodedLength { get; set; }

        [JsonProperty("compression_ratio")]
        public string CompressionRatio { get; set; }
    }
}
